spring:
  datasource:
    url: jdbc:mysql://modu-soccer.cln0znqbq7ya.ap-northeast-2.rds.amazonaws.com:13306/modu_soccer
    username: ${db_user}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

oauth:
  kakao:
    redirect_uri: ${kakao_redirect_url}
