spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/modu_soccer
    username: ${db_user}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always

oauth:
  kakao:
    auth_host: "https://kauth.kakao.com"
    api_host: "https://kapi.kakao.com"
    client_id: ${kakao_client_id}
    client_secret: ${kakao_client_secret}
    redirect_uri: ${kakao_redirect_url}

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        type: trace

aws:
  credentials:
    access_key: ${aws_access_key}
    secret_key: ${aws_secret_key}

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: modu-soccer/local/app

log:
  config:
    path: logs
    filename: spring

jwt:
  secret_key: ${jwt.secret_key}
  expire_in:
    access_token: 99600000
    refresh_token: 986400000

