spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://modu-soccer.cln0znqbq7ya.ap-northeast-2.rds.amazonaws.com:13306/modu_soccer
    username: ${db_user}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

oauth:
  kakao:
    auth_host: "https://kauth.kakao.com"
    api_host: "https://kapi.kakao.com"
    client_id: ${kakao_client_id}
    client_secret: ${kakao_client_secret}
    redirect_uri: ${kakao_redirect_url}

logging:
  config: classpath:logback-spring.xml

aws:
  credentials:
    access_key: ${aws_access_key}
    secret_key: ${aws_secret_key}

log:
  config:
    path: logs
    filename: spring

jwt:
  secret_key: ${jwt.secret_key}
  expire_in:
    access_token: 600000
    refresh_token: 86400000
