# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: On master

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-dev.yml
        env:
          oauth.kakao.client_id: ${{ secrets.KAKAO_CLIENT_ID}}
          oauth.kakao.client_secret: ${{ secrets.KAKAO_CLIENT_SECRET}}
          oauth.kakao.redirect_uri: ${{ secrets.KAKAO_REDIRECT_URL}}
          spring.datasource.username: ${{ secrets.DB_USER}}
          spring.datasource.password: ${{ secrets.DB_PASSWORD}}
          aws.credentials.access_key: ${{ secrets.AWS_ACCESS_KEY}}
          aws.credentials.secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          jwt.secret_key: ${{ secrets.JWT_SECRET_KEY}}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build -x test

      - name: env file
        env:
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: |
          touch .env
          echo export DOCKER_USER_NAME="$DOCKER_USER_NAME" >> .env
          echo export DOCKER_PASSWORD="$DOCKER_PASSWORD" >> .env
          echo export REGISTRY_URL="REGISTRY_URL" >> .env
          echo export TAG=${GITHUB_SHA::7} >> .env

          echo "cat .env"
          cat .env

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
#
      - name: Upload to S3
        run: aws s3 cp --acl private --region ap-northeast-2 ./$GITHUB_SHA.zip s3://modu-soccer/build/$GITHUB_SHA.zip
#
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t modu_soccer .
          docker tag modu_soccer ${{ secrets.REGISTRY_URL }}:${GITHUB_SHA::7}
          docker push ${{ secrets.REGISTRY_URL }}:${GITHUB_SHA::7}

      - name: Code Deploy
        run: aws deploy create-deployment
              --application-name modu-soccer
              --deployment-config-name CodeDeployDefault.OneAtATime
              --deployment-group-name dev
              --s3-location bucket=modu-soccer,bundleType=zip,key=build/$GITHUB_SHA.zip
